In [8]:
import numpy as np
mat1= np.array([[1],[2],[3]])
mat2= np.array([1,2,3,4,5])
mat3 = np.ones([2,3])
mat1[1][0] = 100 #修改
print(mat1)
print(mat1.shape)
print(mat2.shape)
print(mat3)
print('加减乘除')
#加减乘除
mat4 = np.ones([2, 3])
mat5 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(mat4+mat5)
print(mat5-mat4)
print(mat4*mat5)
print(mat5/2)

[[  1]
 [100]
 [  3]]
(3, 1)
(5,)
[[1. 1. 1.]
 [1. 1. 1.]]
加减乘除
[[2. 3. 4.]
 [5. 6. 7.]]
[[0. 1. 2.]
 [3. 4. 5.]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
