In [1]:
import tensorflow as tf

mat0 = tf.constant([[0,0,0]])
mat1 = tf.zeros([1,3]) #创建全0矩阵
mat2 = tf.ones([2,3]) #创建全1矩阵
mat3 = tf.zeros_like(mat2) #创建维度跟mat2一样的全0矩阵
mat4 = tf.fill([2,3], 58) #使用58填充矩阵
mat5 = tf.linspace(0.0, 2.0, 5) # 等分
mat6 = tf.random_uniform([3,4], -1, 5)

with tf.Session() as sess:
    print(sess.run(mat0))
    print(sess.run(mat1))
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))
    print(sess.run(mat5))
    print(sess.run(mat6))

[[0 0 0]]
[[0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[58 58 58]
 [58 58 58]]
[0.  0.5 1.  1.5 2. ]
[[ 3.1378756   1.5033543   1.5578625   1.1679423 ]
 [ 3.3382282   3.133706   -0.08149576  1.6863797 ]
 [-0.09185123 -0.28489947  3.9042702   4.822503  ]]
