In [ ]:
import cv2
import numpy as np

dst = np.zeros((500, 500, 3), np.uint8)

#绘制矩形
cv2.rectangle(dst, (100, 100), (300, 400), (255, 0, 0), -1) # -1 表示填充 正数表示不填充，为线段的宽度

#绘制圆形
cv2.circle(dst, (250, 250), 100, (0, 255, 0), -1)

#绘制椭圆
cv2.ellipse(dst, (300, 300), (150, 100), 45, 0, 180, (255, 255, 255), -1) # 0 0 360 角度(逆时针) 起始角度 终止角度 

#绘制任意多边形
points = np.array([[150, 50], [180, 150], [120, 400], [80, 350], [150, 50]])
print('shape', points.shape)
print(points)
points = points.reshape([-1, 1, 2]) #矩阵转置 [5, 2] -> [5, 1, 2]
print(points)
print('shape', points.shape)
cv2.polylines(dst, [points], True, (128, 128, 128))
cv2.imshow('dst', dst)
cv2.waitKey(0)

shape (5, 2)
[[150  50]
 [180 150]
 [120 400]
 [ 80 350]
 [150  50]]
[[[150  50]]

 [[180 150]]

 [[120 400]]

 [[ 80 350]]

 [[150  50]]]
shape (5, 1, 2)
